apiVersion: agents.x-k8s.io/v1alpha1
kind: Sandbox
metadata:
  name: hermes-agent
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  # service: false
  podTemplate:
    metadata:
      labels:
        agents.x-k8s.io/sandbox-name: hermes-agent
    spec:
      containers:
      - name: hermes
        image: nousresearch/hermes-agent:latest
        args: ["gateway"]
        env:
        - name: HERMES_DASHBOARD
          value: "1"
        - name: HERMES_DASHBOARD_INSECURE
          value: "1" 
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: openrouter-api-key
              key: OPENROUTER_API_KEY
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: hermes-telegram-secrets
              key: bot-token
        - name: TELEGRAM_ALLOWED_USERS
          valueFrom:
            secretKeyRef:
              name: hermes-telegram-secrets
              key: allowed-users
        ports:
        - containerPort: 8642
          name: api
        - containerPort: 9119
          name: dashboard
        volumeMounts:
        - name: data
          mountPath: /opt/data
        - name: hermes-agent-config
          mountPath: /opt/data/config.yaml
          subPath: config.yaml
        - name: hermes-agent-soul
          mountPath: /opt/data/SOUL.md
          subPath: SOUL.md
        - name: host-data
          mountPath: /host/data
          readOnly: true
      volumes:
      - name: hermes-agent-config
        configMap:
          name: hermes-agent-config
      - name: hermes-agent-soul
        configMap:
          name: hermes-agent-soul
      - name: host-data
        hostPath:
          path: /mnt/data/general
          type: Directory
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

