apiVersion: agents.x-k8s.io/v1alpha1
kind: Sandbox
metadata:
  name: hermes-agent
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  # service: false
  podTemplate:
    metadata:
      labels:
        agents.x-k8s.io/sandbox-name: hermes-agent
    spec:
      containers:
      - name: hermes
        image: nousresearch/hermes-agent:latest
        args: ["gateway"]
        env:
        - name: HERMES_DASHBOARD
          value: "1"
        - name: HERMES_DASHBOARD_INSECURE
          value: "1" 
        # - name: HERMES_MODEL
        #   value: "openrouter/owl-alpha"
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: openrouter-api-key
              key: OPENROUTER_API_KEY
        ports:
        - containerPort: 8642
          name: api
        - containerPort: 9119
          name: dashboard
        volumeMounts:
        - name: data
          mountPath: /opt/data
        - name: hermes-agent-config
          mountPath: /opt/data/config.yaml
          subPath: config.yaml
      volumes:
      - name: hermes-agent-config
        configMap:
          name: hermes-agent-config          
      #   - name: skill-k8s-dev
      #     mountPath: /opt/data/skills/custom/k8s-developer.md
      #     subPath: k8s-developer.md
      # volumes:
      # - name: skill-k8s-dev
      #   configMap:
      #     name: hermes-skills
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

