apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-telegram-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: hermes-telegram-secrets
  dataFrom:
    - extract:
        key: hermes-telegram-secrets