---
apiVersion: v1
kind: Namespace
metadata:
  name: operator-lifecycle-manager
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: operator-lifecycle-manager
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/cloudtooling/helm-charts/olm
  ref:
    tag: 0.30.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: operator-lifecycle-manager
  namespace: operator-lifecycle-manager
spec:
  interval: 5m
  releaseName: operator-lifecycle-manager
  chartRef:
    kind: OCIRepository
    name: operator-lifecycle-manager
    namespace: flux-system
  # values:
