---
apiVersion: v1
kind: Namespace
metadata:
  name: operator-lifecycle-manager
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: olm-repo
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/operator-framework/operator-lifecycle-manager
  ref:
    branch: master
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: olm
  namespace: operator-lifecycle-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: ./deploy/chart
      sourceRef:
        kind: HelmRepository
        name: olm-repo
  values:
    # Add any custom values here
