apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "langfuse"
  namespace: "langfuse"
spec:
  taskID: "5"
  configuration:
    zookeeper:
      nodes:
        - host: keeper-clickhouse-langfuse
          port: 2181
    users:
      clickhouse_operator/networks/ip: 0.0.0.0/0
      langfuse_user/networks/ip: 0.0.0.0/0
      langfuse_user/password:
        valueFrom:
          secretKeyRef:
            name: langfuse-clickhouse-creds
            key: password
    clusters:
      - name: "langfuse"
---
apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: clickhouse-langfuse
spec:
  configuration:
    clusters:
      - name: "langfuse"
