apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.io/charts/
      chart: cloudnativepg
      targetRevision: 0.26.0
      helm:
        releaseName: cloudnativepg
        valuesObject:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudnativepg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
