apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
      server {
          listen 443 ssl;

          ssl_certificate         /etc/nginx/certs/client.crt;
          ssl_certificate_key     /etc/nginx/certs/client.key;

          ssl_client_certificate  /etc/nginx/certs/ca.crt;
          ssl_verify_client       on;

          location / {
              proxy_pass http://docker-registry.docker-registry.svc.cluster.local:5000;
          }
      }
    }


