apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: exa-search
  namespace: kagent
spec:
  # transportType: http
  transportType: stdio
  deployment:
    image: mcp/exa:latest
    cmd: /bin/sh
    args:
      - -c
      - exec node dist/stdio.cjs
    secretRefs:
      - name: exa-credentials
    port: 3000