apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: exa-search
  namespace: kagent
spec:
  transportType: http
  deployment:
    image: mcp/exa:latest
    cmd: /bin/sh
    args:
      - -c
      - export EXA_API_KEY=$(cat /etc/secrets/EXA_API_KEY) && exec node dist/stdio.cjs
    secretRefs:
      - name: exa-credentials
    # port: 3000