---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-secret
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgDCCcX4GYjhQqdkcmAP5wVM5gGUiLbYt8bv7pPv/vx4FFDDVgy3iKWRSk/iqnnM8nP7cxUraOLIHnN6wR7ZAdUAg1QRONXcdHb0frqKZ25hMh3PivNn45amF8NTbdFq42nBWpRUraT15JmfKOLF8xhzgja8q8hGOSDZ8DWQOsRoBHzTbYCTd8JvODbqPEFCsl3aDSDPvwrxkALdomo19ErVwtkqLWq2S53c3rFa2JpVMQZzqDqhLdUIZ5DxAxnhytidxfWk+0I4QqmIUVvOjmArqDAUCJSGf9xf5Ou/OzXmhN0sWk0UWFbp7ZpQcB0PqEBHExue4zZomWRPH5dTJM0imrV4bhQzP2TL2ZjT9ueZ5K5WENdvutktcpH8PGTxywk/vft+U/4qobdsIEkkuOmu/cfgT+UfVU6wkAv5/a4SfXxjbPGV3t5OCNnrhjFuqIKRi7+TfOROsDFJoMlgoOC4IOzhxhRCwjFbOFwfDDiBnrYQqfXP6fbx1Lm9IwMVTvX/fFdUCWbePszLnhc6zlz1BBrro982VVZlkFpn2R9EwL5dNdShnc2VQA/riux1FMyZMfltTtfGIUplstuCihZF3YzH0biQethxt2M/OLymJeJqt6H7hmL7e4NgICkeejs/RkPmfVbi2eEAoxWE66SAu/oT2xsRZCtdHcsnUjXa9VdIaHO/+RFREvc2xXSXLEpctrsJ+Ph8poBZhxo=
    admin-user: AgCCukBJayiQQ9ETv0r+emuXz9miJz6XHh934a6bdAAb6VrVyYtE9WdRr8/UeMCIg2mST84++LnpwiAGKx5e4RC/au4lZyeDcYajDqfDCyDKjFScifiBBhNRCA4+siS4kzr1CpmWqZuoRNxVzbfdSUOCS1Obw+ayKeWxrwrwtmjIpwetPou6N4ZCP+eo/dcCE2G4XQ1qspfaXq3Nlx+/3ApBpSnldtMYoCQ0Jre/7tJpXRcxMLV01zuu5pQzA5f22kpuy39bW0wDJn8BQpjGNewSeEcJeKuC70UPqrDN2u2LD1hUbvmhIDktNnqgS5g5st0BkELNRQpMWbfS5anHJGycP5qIAfJ2fqVt3bbREioOsv74A5/kv+E01VlI6dmhBlQpZSY0vMSCBfFy0FTkNalY6mw6IbYkeey3Vx2CuU0lT7KORaOCZ78JnhHeN4OegQmzjR1bO27QHXmFJjwhsZGNkDrLi933i8Yc63c5eYQbDDLbDY09ulldf0Wt+2tjyfbl7Oqo5B5Stmno+WBrBe0I0lj2iNyXoPk4sX+Eeib6yjf3YQXR6Y8Pco+wh1SmLtYeZ61AdImR8W3+uHsmNFFyPtFuwTfcLEFxdRRaufmM3QBCgQ/i7LzYExROYBLZHx84lUz26vSCWpAhQlgqMzNw/oHoh/VJz/LPn4dW+RuNojWko1lJNyH2ftpnScW0XN/w4qQ5XA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-secret
