apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  namespace: grafana
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-secret
spec:
  encryptedData:
    admin-password: AgAOSb5aVf7hiqN2sX2jKARBBLsz5hoq2mUDgJTvNmmaFw8g41qVWnoCQo8yUrusZ8IdIg4aVvbgVbhlDlgj0axsI+mEu+VMCXPq2afp7Oi+aqDwdFeTpxj8q+WQK1GTSTWjlzNLx9OfAlYuq7yKlybJ2cnrsEL7T/ScfqcrM3MidaRlmwy69+BvNpdTW5TNd6BEE/SQwLo9OpxeQ1F9mY4+r3skSbm+0ruc0RRzyt8uXwJZlDmre3Z+qY3K7HVjEi3ym/bD7hDVxdmUz3Q1sIf8mkFc2hOY7xLZ1vdYlPt+c3xUFpDEWsSmnTmBAA9ILv0gNUsxxBRhIUHYO0/7W8vaw03kHIm39GivLcz5cDWBbvjOrYfZ6zSnNIC0ENNi/PpMlFxR+8BXCwaNL6t93N2HU7BCdFPWDcnRM61ipqEiVymh7lnN8ptV3g57WsShiMFtLd+qO9Vk+RodnWfR0oIMl4rcZJAAsbjVozfknqjKFdB/61ZiaewFREPZlhWL0uWzEFxZbb+X0Fn0m2VecAfEigDn3miuonj4USeIqJAgl1x2903V2147gmQDroCw14BLwvmkgLTHthQFbzDlRgeRf+Zm6yptrDEifUJu3n6kbHqOnb4hR9K+F5jubyVMATaXzOfKDAm0B2zxTk4UD+oEBBdxgmQCZ3l3woUp6TCsLULW1tMxFug20laTpxUlko0T56yrCx9thzK53ug=
    admin-user: AgACcQ1HoTo1N4s1olCphULmXop7tmFR3sfQXlPe1YG3uQKPwNWfdU3UL9/kShVZIPM+sCMC028vSI72GZRfLgs/JfMnVgevLeU6S0SdMfMzDBrkAbGrMg8txy8lSNpwgAoG8aO7ze7jxzyQZSPW3LFydXdAbgKM/FHpXuR7fWvSSFiQpYgtC9j060aSFbhrTX13fXq51EEDT6B4mt904W2X3j6Kw2UMmzz6PbRb0rV2yIaYO/S+ZF3K/6gCzNG20ZnnOyTQEeUE/Lsdmh8NJ93TphzZyLkHOtPrV2qe25kjGBOygW5b85T+dBPZtY15CzK5aF0Lq7h+I101j3gUybQM+qGXpaOgFpS2HlNcs+GbvWacMXren0txl5+5yfivlPaGjMD0ofGMKzz6E2HxMN5HscVR+RkpPoMIZCM0XdS9JJMbEZ4wsKdmxhaVFLDzcCwpKJ6WwY2W/OTcY1sRD29Cw6oEjCWfXm8f8pkDZ6OyGeWGVweoCM9x19VPhiiuM3+/q4ldwrNdktzWGnC/IoA1CferfgVvStoOzxfhq92uvWwUXZExM72h9bPDxe1d3MzMzAoXFpUaEVv9w3q9NFmFo7YzmpRfIjSymGBp0ZUvntp3KYRG113cGAPa0GXLMZry6EYO+VmeJgSQKvWO5hLpnOMLOPGAieBa2bXXzMJWqheQUx0HYBq7Bb4vpzTTcfUc0sUyTg==
  template:
    metadata:
      # namespace: grafana
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-secret
