apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-password
  namespace: sealed-secrets
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgBG8RQ99Ss5GXmwrRLoF6Nuq3Ly0A5JQo/4MKzUs39EcYSJqWCWowQVUHc+rUHdR0R/slY2MYX3wU4CkXP55axynuemi9emhGsNLZJXni1qzyHGg1h558moR96s915N15TCDFPzxz6UgjqFLhzbgpqP5UwyUsy9Yh47NoYNmUYheXu8C0NAEOvy7F7gxsznFTZOJWP1XR7yGcGkHZpiKnRs0cx+sF8hxU9Bn10DjHC78hQ7CylIaNZ6FTxBzwTe6/BxIiESMv7B2WHRq78P0+NOQKygOERAwVrgmlNcdxPqsFBvamlEPNjvQuOk9WiHlimuv8NXGrIfd0rSFjnxJ9FcG3JuAeY1MRajOG1IrBZTG3rpCkQgbpIUXc5upSNeuHov6AClko27VhHvwHWKuzCYmBX8YMCREj5mNHhosFvn4M0sEN9UINKS/TfT4TeNRSxdS04Mv81VCvvCR+rv8I83ZnmJKmwuu004JmnUMEiA/gMKRybtjwUvqGzEmIsiDf1wWFFp6G6LBNofunRXesA4awqxki0Bwd2iWqx3x5ahnwUbn2G4JXv68MMJIM2GgDnNn+WXm9xVCsaROVgJjdSmPv8BodtYvCqZCcv1qvq1ACW5Rops+KZgwKIEtVX9VMJeWQ3LuCGHwJzA0HoTQzCq/3i7Ai7enuWrBD1P8KLwOJYS2qMo9xFsmAVP65LcqadvDf3dmFFaqQ==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-password
      namespace: sealed-secrets

