apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-password
  namespace: pihole
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgAC9riEan3qeotL72G8q+bWFvkjru0cSizAWECBymQiSOjbxxQGRe2QuKEFcXkqNqW7grXpomitrgq1nelTPaqHLzqnRIYJvdc/DKG+GakYf1GfvQ/717cuZ0+352rVtH41PV5s0TnaVaAQFxq05FbA9NAb+MHq6hEdkTBKAlDhAqnDkPfeAn0kusi/aMpde70JcnvIZ8y2aLdokWP0CA1J8ZWnmqyAi/YL4PC4jNaOw1UWirpbPH4sgoCzEgsoAJ/PYZBfZnWt8nOGrpQZp1ws6Ky00Kf8Y/3C+luT7ol/4lfNx3H5SqNKG8WHzD6FbhlSh/bqaFkubxxfENBfzLEDuPoUTIeYieILpDerJW9/93dwWmXJDcZ62F9APcy5e0ePMXf+NoPh68u1vI6EfANApj66LX1stlCiKB8dateNkJRcdmoFZkubN6kFmXOZLQXmrkaaR8je+0Z3T3S5Rs6A8+vtHMcdBZTJywnqkrcYAHx7OMptB9vnsI/Z7WPU3IcuHirZAJl17CsYXkexKYni4mSEaiRUgEL2NV0d1W2JPLPR/76MMwG4IBCudHE4Hg6i9a3ZlBb+tmetKLoJnB1WFOBYgp+e4VkRGU9urW1Pi7pQo6C8wey0ciHTT5YcGyghD5BCBPWmRWDy3fYSaASYj7sec52m1n6RCfbDu3jxQbv34/mA0a0aLokxqIJndDipD6DsmK32JA==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-password
      namespace: pihole
