apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/network
  labels:
    testing.upbound.io/example-name: network_1
  name: network-1
spec:
  forProvider:
    autoCreateSubnetworks: false
  providerConfigRef:
    name: providerconfig-gcp
---
apiVersion: compute.gcp.upbound.io/v1beta2
kind: Subnetwork
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta2/subnetwork
  labels:
    testing.upbound.io/example-name: subnet_1
  name: subnet-1
spec:
  forProvider:
    ipCidrRange: 10.0.0.0/24
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: network_1
    region: us-east4