apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: keepercluster
spec:
  replicas: 1
  dataVolumeClaimSpec:
    resources:
      requests:
        storage: 1Gi
---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: clickhousecluster
spec:
  replicas: 1
  dataVolumeClaimSpec:
    resources:
      requests:
        storage: 1Gi
  keeperClusterRef:
    name: keepercluster
