apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  mode: daemonset
  # image: otel/opentelemetry-collector-k8s
  config:
    processors:
      deltatocumulative:
        max_stale: 5m
    receivers:
      filelog:
        include:
        - /var/log/pods/*/*/*.log
      hostmetrics:
        collection_interval: 30s
        scrapers:
          cpu: {}
          memory: {}
          disk: {}
          filesystem: {}
          network: {}
          load: {}
          paging: {}
          process: {}
    exporters:
      otlphttp/vmcluster:
        metrics_endpoint: http://vminsert-vmcluster.victoria-metrics-operator.svc:9481/opentelemetry/v1/metrics
        compression: gzip
        encoding: proto
      otlphttp/vlcluster:
        logs_endpoint: http://vlinsert-vlcluster.victoria-metrics-operator.svc:8480/insert/opentelemetry/v1/logs
        compression: gzip
        encoding: proto
    service:
      pipelines:
        logs:
          receivers: [filelog]
          exporters: [otlphttp/vlcluster]
        metrics:
          receivers: [hostmetrics]
          processors: [deltatocumulative]
          exporters: [otlphttp/vmcluster]