# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: longhorn-static-pv
# spec:
#   capacity:
#     storage: 10Gi  # Set your desired storage size
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain  # Retain data when the PV is deleted
#   storageClassName: longhorn-static  # Use the 'longhorn-static' storage class
#   longhorn:
#     volumeName: pv-longhorn-static-1  # Replace with the name of your Longhorn volume
#   mountOptions:
#     - discard
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-static-pvc-1
  namespace: jellyfin  # Use the appropriate namespace for your use case
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Ensure the requested storage size matches the PV's capacity
  storageClassName: longhorn-static  # Use the 'longhorn-static' storage class

