apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  mode: daemonset  # This creates a DaemonSet
  # image: otel/opentelemetry-collector-k8s
  config: |
    receivers:
      filelog:  # for container logs
        include:
          - /var/log/pods/*/*/*.log
      hostmetrics:
        collection_interval: 30s
        scrapers:
          cpu: {}
          memory: {}
          disk: {}
          filesystem: {}
          network: {}
          load: {}
          paging: {}
          process: {}

    exporters:
      otlphttp/vmcluster:
        metrics_endpoint: http://vmselect-vmcluster.default.svc.cluster.local:8481/opentelemetry/v1/metrics
        compression: gzip
        encoding: proto

      otlphttp/vlcluster:
        logs_endpoint: http://vlselect-vlcluster.default.svc.cluster.local:8481/insert/opentelemetry/v1/logs
        compression: gzip
        encoding: proto

    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [otlphttp/vlcluster]

        metrics:
          receivers: [otlp]
          exporters: [otlphttp/vmcluster]