apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-lab-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      revision: HEAD
      files:
      - path: ./apps/*.yaml
  template:
    metadata:
      name: '{{.path.filename | trimSuffix ".yaml"}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/UriZafrir/home-lab-cluster.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          selfHeal: true
          allowEmpty: false
          prune: true
        syncOptions:
        - CreateNamespace=true