apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: temporal
spec:
  instances: 1
  storage:
    size: 10Gi
  managed:
    roles:
    - name: app
      ensure: present
      login: true
      createdb: true
      passwordSecret:
        name: postgres-app