apiVersion: v1
kind: ConfigMap
metadata:
  name: cozystack
  namespace: cozy-system
data:
  bundle-name: "distro-full"
  bundle-disable: "snapshot-controller"
  ipv4-pod-cidr: "10.244.0.0/16"
  ipv4-svc-cidr: "10.96.0.0/16"
  root-host: "192-168-123-74.nip.io"
  api-server-endpoint: "https://192-168-123-74.nip.io:6443"