apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgvector
spec:
  storage:
    size: 10Gi
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: 18

  postgresql:
    extensions:
      - name: pgvector
        # FIX: Explicitly supply the OCI extension container image
        image: "ghcr.io/cloudnative-pg/postgres-extensions/pgvector:18"