apiVersion: v2
name: cilium
description: A Helm chart with cert-manager as a dependency
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: cilium
    version: "1.18.0"
    repository: "https://helm.cilium.io/"