# https://fluxcd.io/flux/guides/helmreleases/#using-a-chart-reference
---
apiVersion: v1
kind: Namespace
metadata:
  name: spark
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-spark
  namespace: flux-system
spec:
  interval: 10m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts/spark
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spark
  namespace: spark
spec:
  interval: 5m
  chart:
    spec:
      chart: spark
      sourceRef:
        kind: HelmRepository
        name: bitnami-spark
      # version: 'v0.0.0-latest'
  values:



# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: spark
# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: OCIRepository
# metadata:
#   name: bitnami-spark
#   namespace: flux-system
# spec:
#   interval: 10m
#   url: oci://registry-1.docker.io/bitnamicharts/spark
#   ref: 
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: spark
#   namespace: spark
# spec:
#   interval: 5m
#   releaseName: spark
#   chartRef:
#     kind: OCIRepository
#     name: bitnami-spark
#     namespace: flux-system
#   values:


# apiVersion: v1
# kind: Namespace
# metadata:
#   name: envoy-gateway-system
#   annotations:
#     openshift.io/requester: system
# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: HelmRepository
# metadata:
#   name: envoyproxy
#   namespace: envoy-gateway-system
# spec:
#   interval: 5m
#   type: oci
#   url: oci://docker.io/envoyproxy
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: eg
#   namespace: envoy-gateway-system
# spec:
#   install:
#     remediation:
#       retries: 3
#   upgrade:
#     remediation:
#       retries: 3
#   chart:
#     spec:
#       chart: gateway-helm
#       sourceRef:
#         kind: HelmRepository
#         name: eg
#       version: 'v0.0.0-latest'
#   interval: 1m0s

