apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-spark
  namespace: flux-system
spec:
  interval: 10m
  url: oci://registry-1.docker.io/bitnamicharts/spark
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spark
  namespace: spark
spec:
  interval: 5m
  releaseName: spark
  chartRef:
    kind: OCIRepository
    name: bitnami-spark
  chart:
    spec:
      chart: spark # The name of the chart within the OCI repository
      sourceRef:
        kind: OCIRepository
        name: bitnami-spark # Reference to the OCIRepository defined earlier
        namespace: flux-system
  values:

---
apiVersion: v1
kind: Namespace
metadata:
  name: spark

