apiVersion: v1
kind: Namespace
metadata:
  name: spark
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spark
  namespace: spark
spec:
  interval: 5m
  chart:
    spec:
      chart: spark
      version: ">=9.3.0" # Replace with the desired version from the Bitnami repository
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
