apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: exa
spec:
  mcp:
    targets:
      - name: exa
        static:
          host: exa-search.kagent.svc.cluster.local
          port: 3000
          protocol: StreamableHTTP
