apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: exa
spec:
  mcp:
    targets:
      - name: exa
        selector:
          services:
            matchLabels:
              app.kubernetes.io/name: exa-search
