apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.elastic.co
      chart: eck-operator
      targetRevision: 2.16.0
      helm:
        releaseName: elastic-operator
        valuesObject:
    - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      targetRevision: HEAD
      path: extras/elastic
  destination:
    server: "https://kubernetes.default.svc"
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
