apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/UriZafrir/home-lab-cluster.git
    targetRevision: HEAD
    path: extras/knative
  destination:
    server: "https://kubernetes.default.svc"
    namespace: knative
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
