#first install iscsi
#apt-get install open-iscsi
#systemctl enable iscsid
#systemctl start iscsid
#systemctl status iscsid
#https://longhorn.io/docs/1.7.2/deploy/install/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.7.2
    helm:
      releaseName: longhorn
      valuesObject:
        defaultSettings:
          defaultDataPath: /mnt/data
        persistence:
          defaultClass: false
        preUpgradeChecker:
          jobEnabled: false
        service:
          ui:
            type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/ports/0/nodePort
