apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-hpa-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  sources:
    - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      targetRevision: HEAD
      path: extras/nginx-hpa-test
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx-hpa-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
