apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default
  source:
    chart: radarr
    repoURL: https://charts.alekc.dev
    targetRevision: 1.10.0
    helm:
      releaseName: radarr
      valuesObject:
        image:
          repository: lscr.io/linuxserver/radarr
          tag: latest
        service:
          type: LoadBalancer  
        
  destination:
    server: "https://kubernetes.default.svc"
    namespace: radarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
