#https://github.com/ray-project/kuberay/blob/master/helm-chart/kuberay-operator/README.md
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberay-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kuberay-operator
    repoURL: https://ray-project.github.io/kuberay-helm/
    targetRevision: 1.1.0
    helm:
      releaseName: kuberay-operator
      valuesObject:
        installCRDs: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kuberay-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true 
