apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: gateway
  # annotations:
  #   networking.istio.io/service-type: NodePort
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-cilium-gateway-to-victoria-metrics-operator
  namespace: victoria-metrics-operator  # Namespace of the backend service
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: gateway  # Namespace of the HTTPRoute
  to:
  - group: ""
    kind: Service  # Allow referencing Kubernetes Services
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-route-cilium
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - "vmselect.192.168.122.101.nip.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: keycloak-service
          namespace: keycloak 
          port: 8481