apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default
  source:
    #from https://github.com/backstage/backstage
    repoURL: https://github.com/UriZafrir/home-lab-cluster.git
    targetRevision: HEAD
    path: extras/backstage
    helm:
    #   valueFiles:
    #     - values.yaml
      values: |
        service:
          type: LoadBalancer
        image:
          repository: ghcr.io/spotify/backstage
          tag: 1.42.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
