apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      targetRevision: ubuntu
      path: extras/bookinfo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: bookinfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient