#https://www.haproxy.com/documentation/haproxy-configuration-tutorials/security/authentication/client-certificate-authentication/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://haproxytech.github.io/helm-charts
      chart: haproxy
      targetRevision: 1.28.0
      helm:
        releaseName: haproxy
        valuesObject:
          service:
            type: LoadBalancer
          extraVolumes:
            - name: client-cert
              hostPath:
                path: /etc/docker/certs.d/cert-and-key.pem
                type: File
            - name: ca-cert
              hostPath:
                path: /etc/docker/certs.d/registry-192-168-122-101.nip.io/ca.crt
                type: File
          extraVolumeMounts:
            - name: client-cert
              mountPath: /certs/client-crt-and-key.pem
              readOnly: true
            - name: ca-cert
              mountPath: /certs/ca.crt
              readOnly: true
          config: |
            global
              log stdout local0

            defaults
              mode http
              timeout client 5m
              timeout connect 10s
              timeout server 5m
              option forwardfor

            frontend fe_main
              bind :80
              redirect scheme https code 301 if !{ ssl_fc }
              bind :443 ssl crt /certs/client-crt-and-key.pem verify required ca-file /certs/ca.crt
              default_backend docker_registry

            backend docker_registry
              http-request set-header X-Forwarded-Proto https if { ssl_fc }
              server docker-registry docker-registry.docker-registry.svc.cluster.local:5000 check
  destination:
    server: "https://kubernetes.default.svc"
    namespace: haproxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true



# rm -rf /etc/docker/certs.d
# mkdir -p /etc/docker/certs.d/registry-192-168-122-101.nip.io
# cd /etc/docker/certs.d

# openssl req -newkey rsa:2048 -nodes -x509 -days 3650 \
#   -keyout privateCA.pem -out ca.crt \
#   -subj "/CN=MyOrg-CA/C=IL"

# openssl req \
#   -newkey rsa:2048 \
#   -nodes \
#   -subj "/CN=registry-192-168-122-101.nip.io" \
#   -keyout client.key \
#   -out client.csr \
#   -addext "subjectAltName=DNS:registry-192-168-122-101.nip.io"

# openssl x509 -req -in client.csr -CA ca.crt -CAkey privateCA.pem \
#   -CAcreateserial -out client.cert -days 3650 \
#   -extfile <(echo "subjectAltName=DNS:registry-192-168-122-101.nip.io")


# openssl x509 -noout -text -in ca.crt 
# openssl x509 -noout -text -in client.cert

# cp ca.crt registry-192-168-122-101.nip.io/
# cp client.cert registry-192-168-122-101.nip.io/
# cp client.key registry-192-168-122-101.nip.io/
# cat client.cert >> cert-and-key.pem
# cat client.key >> cert-and-key.pem
# sudo curl https://registry-192-168-122-101.nip.io/v2/   --cacert ca.crt   --cert client.cert   --key client.key   -vvk

# systemctl restart docker
  