apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/kagent-dev/kagent/helm/kagent-crds
      targetRevision: 0.9.1
      chart: kagent-crds
      helm:
        releaseName: kagent-crds
        valuesObject:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
