apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-add-ons-http-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      targetRevision: ubuntu
      path: extras/keda-add-ons-http-test
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keda-add-ons-http-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true