apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: default
  sources:
    - repoURL: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway
      chart: kgateway
      targetRevision: 2.3.0-main
      helm:
        releaseName: kgateway
        valuesObject:
          # inferenceExtension:
          #   enabled: true
          # agentgateway:
          #   enabled: true
    - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      targetRevision: ubuntu
      path: extras/kgateway
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kgateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
