apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-crd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/kserve/charts/kserve-crd
      chart: kserve-crd
      targetRevision: v0.16.0
      helm:
        releaseName: kserve-crd
        valuesObject:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
