apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.runix.net/
      chart: pgadmin4
      targetRevision: 1.62.0
      helm:
        releaseName: pgadmin
        valuesObject:
          service:
            type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: pgadmin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
