apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-unsealer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.bakito.net
      chart: vault-unsealer
      targetRevision: 0.4.1
      helm:
        releaseName: vault-unsealer
        valuesObject:

  destination:
    server: "https://kubernetes.default.svc"
    namespace: openbao
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
