apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse"
spec:
  configuration:
    users:
      clickhouse_operator/networks/ip: 0.0.0.0/0
    clusters:
      - name: "clickhouse"
