apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-sandbox
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubernetes-sigs/agent-sandbox.git
      targetRevision: main
      path: helm
      helm:
        releaseName: agent-sandbox
        valuesObject:
          image:
            tag: v0.5.0rc1
          controller:
            extensions: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: agent-sandbox-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

