#argocd login 192.168.70.180:30443
#argocd appset generate applicationset-cluster-and-git-file.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-cluster-and-git-file
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # matrix 'parent' generator
  # git generator, 'child' #1
  - git:
      repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      revision: talos
      files:
        - path: applicationset-apps/*.yaml
          # cluster generator, 'child' #2
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/UriZafrir/home-lab-cluster.git
        targetRevision: talos
        path: applicationset-apps/{{.name}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.name}}'
      # syncPolicy:
      # {{- if not .manualSync }}
      #   automated:
      #     prune: true
      #     selfHeal: true
      # {{- end }}