#argocd login 192.168.70.180:30443
#argocd appset generate applicationset-cluster-and-git-file.yaml
#https://gotemplate.io/
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-cluster-and-git-file
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=invalid"]
  generators:
  - git:
      repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      revision: talos
      files:
      - path: 'applicationset-apps/**/.argocd.yaml'
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/UriZafrir/home-lab-cluster.git
        targetRevision: talos
        path: applicationset-apps/{{.name}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace | default .name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
  templatePatch: |
    {{- if eq .name "cert-manager" }}
    spec:
      syncPolicy:
        automated:
          enabled: false
          prune: false
          selfHeal: true
    {{- end }}

  # templatePatch: |
  #   {{- if eq .name "cert-manager" }}
  #   spec:
  #     syncPolicy:
  #       manual:
  #         prune: false
  #         selfHeal: true
  #   {{- end }}
    # metadata:
    #   {{- if .labels }}
    #   labels:
    #     {{- range $key, $value := .labels }}
    #     {{ $key }}: "{{ $value }}"
    #     {{- end }}
    #   {{- end }}
    # spec:
    #   syncPolicy:
    #     {{- if and .syncPolicy (eq .syncPolicy "automated") }}
    #     automated:
    #       prune: true
    #       selfHeal: true
    #     {{- end }}
    #     {{- if .syncOptions }}
    #     syncOptions:
    #     {{- range .syncOptions }}
    #     - {{ . }}
    #     {{- end }}
    #     {{- end }}
    # {{- if .ignoreDifferences }}
    # ignoreDifferences:
    #   {{- range .ignoreDifferences }}
    #   - group: {{ .group }}
    #     kind: {{ .kind }}
    #     name: {{ .name }}
    #     jsonPointers:
    #       {{- range .jsonPointers }}
    #       - {{ . }}
    #       {{- end }}
    #   {{- end }}
    # {{- end }}

