#argocd login 192.168.70.180:30443
#argocd appset generate applicationset-cluster-and-git-file.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-cluster-and-git-file
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: https://github.com/UriZafrir/home-lab-cluster.git
              revision: talos
              files:
                - path: applicationset-apps/*.yaml
          # cluster generator, 'child' #2
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{.name}}-{{.cluster.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/UriZafrir/home-lab-cluster.git
        targetRevision: talos
        path: applicationset-apps/{{.name}}
      destination:
        server: '{{.cluster.name}}'
        namespace: '{{default .name .targetNamespace}}'
      # syncPolicy:
      # {{- if not .manualSync }}
      #   automated:
      #     prune: true
      #     selfHeal: true
      # {{- end }}