apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 1.0.7
    helm:
      releaseName: argo-workflows
      valuesObject:
        server:
          authModes:
            - server
          serviceType: LoadBalancer
    - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      targetRevision: ubuntu
      path: extras/argo-workflows
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
