apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/backstage/backstage.git
    targetRevision: HEAD
    path: contrib/kubernetes/basic_kubernetes_example_with_helm
    # helm:
    #   valueFiles:
    #     - values.yaml
      # values: |
      #   service:
      #     type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
