apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: oci://ghcr.io/backstage/charts/backstage
    targetRevision: 2.6.0
    chart: backstage
    helm:
      releaseName: backstage
      valuesObject:
        service:
          type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
