apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-extras
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # annotations:
  #   argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      targetRevision: ubuntu
      path: extras/cilium
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cilium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true