apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.cilium.io/
      chart: cilium
      targetRevision: 1.19.0-pre.0
      helm:
        releaseName: cilium
        valuesObject:
          kubeProxyReplacement: true
          # l2announcements:
          #   enabled: true
          # externalIPs:
          #   enabled: true
          operator:
            replicas: 1  # Uncomment this if you only have one node
          # rollOutPods: true
          # rollOutCiliumPods: true
          # k8sClientRateLimit:
          #   qps: 50
          #   burst: 200
          # gatewayAPI:
          #   enabled: true
          # nodePort:
          #   enabled: true
            # hostNetwork:
            #   enabled: true
          # envoy:
          #   securityContext:
          #     capabilities:
          #       keepCapNetBindService: true
    # - repoURL: https://github.com/UriZafrir/k3d-testing.git
    #   targetRevision: HEAD
    #   path: gitops/extras/cilium
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  # syncPolicy:
  #   manual:
  #     prune: true
  #     selfHeal: true