apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.crossplane.io/master/
      chart: crossplane
      targetRevision: 1.20.0-rc.0.31.gce27e653e
      helm:
        releaseName: crossplane
        valuesObject:
          # installCRDs: true
          # podDnsPolicy: "ClusterFirst"
    - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      targetRevision: HEAD
      path: extras/crossplane
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
