apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://twuni.github.io/docker-registry.helm
      chart: docker-registry
      targetRevision: 3.0.0
      helm:
        releaseName: docker-registry
        valuesObject:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: docker-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
