apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.joxit.dev
      chart: docker-registry-ui
      targetRevision: 1.1.3
      helm:
        releaseName: docker-registry-ui
        valuesObject:
          ui:
            service:
              type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: docker-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
