apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: oci://code.forgejo.org/forgejo-helm/forgejo
      chart: forgejo
      targetRevision: 16.2.1
      helm:
        releaseName: forgejo
        valuesObject:
          service:
            http:
              type: LoadBalancer
            ssh:
              type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: forgejo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
