apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts/
      chart: grafana
      targetRevision: 11.3.6
      helm:
        releaseName: grafana
        valuesObject:
          service:
            type: LoadBalancer
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
              - name: VictoriaMetrics Cluster
                type: victoriametrics-metrics-datasource
                url: http://vmselect-vmcluster.victoria-metrics-operator.svc:8481/select/0/prometheus
                access: proxy
                isDefault: true
          grafana.ini:
            users:
              default_theme: light
    # - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
    #   targetRevision: HEAD
    #   path: extras/grafana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
