apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.0.0
      helm:
        releaseName: grafana
        valuesObject:
          service:
            type: LoadBalancer
          serviceMonitor:
            enabled: true
    - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      targetRevision: HEAD
      path: extras/grafana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
