apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.0.0
      helm:
        releaseName: grafana
        valuesObject:
          service:
            type: LoadBalancer
          serviceMonitor:
            enabled: true
          datasources:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
              access: proxy
              isDefault: true
          grafana.ini:
            users:
              default_theme: light
          admin:
            existingSecret: grafana-secret
    # - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
    #   targetRevision: HEAD
    #   path: extras/grafana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
