#https://www.haproxy.com/documentation/haproxy-configuration-tutorials/security/authentication/client-certificate-authentication/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://haproxytech.github.io/helm-charts
      chart: haproxy
      targetRevision: 1.28.0
      helm:
        releaseName: haproxy
        valuesObject:
          service:
            type: LoadBalancer
          extraVolumes:
            - name: client-cert
              hostPath:
                path: /etc/docker/certs.d/registry-192-168-122-101.nip.io/cert-and-key.pem
                type: File
            - name: ca-cert
              hostPath:
                path: /etc/docker/certs.d/registry-192-168-122-101.nip.io/ca.pem
                type: File
          extraVolumeMounts:
            - name: client-cert
              mountPath: /certs/client-crt-and-key.pem
              readOnly: true
            - name: ca-cert
              mountPath: /certs/ca.crt
              readOnly: true
          config: |
            global
              log stdout local0

            defaults
              mode http
              timeout client 5m
              timeout connect 10s    # ← ADD THIS
              timeout server 5m
              option forwardfor

            frontend fe_main
              bind :80
              redirect scheme https code 301 if !{ ssl_fc }
              bind :443 ssl crt /certs/client-crt-and-key.pem verify required ca-file /certs/ca.crt
              default_backend docker_registry

            backend docker_registry
              http-request set-header X-Forwarded-Proto https if { ssl_fc }
              server docker-registry docker-registry.docker-registry.svc.cluster.local:5000 ssl verify required ca-file /certs/ca.crt check
  destination:
    server: "https://kubernetes.default.svc"
    namespace: haproxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
