apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.18.3
      helm:
        releaseName: harbor
        valuesObject:
          expose:
            # Set how to expose the service. Set the type as "ingress", "clusterIP", "nodePort" or "loadBalancer"
            # and fill the information in the corresponding section
            type: loadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    # - ServerSideApply=true