apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.18.3
      helm:
        releaseName: harbor
        valuesObject:
          expose:
            # Set how to expose the service. Set the type as "ingress", "clusterIP", "nodePort" or "loadBalancer"
            # and fill the information in the corresponding section
            type: loadBalancer
            loadBalancer:
              IP: 192.168.122.201
            # type: route
            # type: nodePort
            tls:
              enabled: false
          externalURL: http://192.168.122.201
            # route:
            #   parentRefs:
            #     - name: kgateway-gateway
            #       namespace: kgateway-system
            #   hosts:
            #     - harbor.192.168.122.200.nip.io
          # externalURL: http://harbor.192.168.122.200.nip.io
          # externalURL: http://192.168.64.105:30002


  destination:
    server: "https://kubernetes.default.svc"
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    # - ServerSideApply=true