apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.14.2
    helm:
      releaseName: ingress-nginx
      valuesObject:
      # these three are needed for host-networking - opening port 80 and 443 on host, sharing dns with host, and running as a daemon set so because only a single process can bind to a port
      # https://kubernetes.github.io/ingress-nginx/deploy/baremetal/#via-the-host-network
        controller:
          hostNetwork: true
          kind: DaemonSet
          dnsPolicy: ClusterFirstWithHostNet
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

