apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # annotations:
  #   argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: https://kiali.org/helm-charts
      chart: kiali-operator
      targetRevision: 2.17.0
      helm:
        releaseName: kiali
        valuesObject:
          cr:
            create: true 
            namespace: monitoring
            spec:
              external_services:
                prometheus:
                  url: "http://kube-prometheus-stack-prometheus.monitoring:9090/"
                grafana:
                  enabled: true
                  internal_url: 'http://kube-prometheus-stack-grafana.monitoring:80/'
                  auth:
                    type: basic
                    ca_file: ""
                    insecure_skip_verify: false
                    password: secret:kube-prometheus-stack-grafana:admin-password
                    token: ""
                    type: "basic"
                    use_kiali_token: false
                    username: secret:kube-prometheus-stack-grafana:admin-user
                  health_check_url: ""
              deployment:
                cluster_wide_access: true
                service_type: LoadBalancer
                network_policy:
                  enabled: true
              auth:
                strategy: "anonymous"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
