apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: https://kiali.org/helm-charts
      chart: kiali-server
      targetRevision: 2.17.0
      helm:
        releaseName: kiali
        valuesObject:
          auth:
            strategy: "anonymous"
          deployment:
            service_type: LoadBalancer
        external_services:
          prometheus:
            # Prometheus service name is "metrics" and is in the "telemetry" namespace
            url: "http://prometheus-server.monitoring:80/"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    # - CreateNamespace=true
