apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      targetRevision: HEAD
      path: extras/keycloak
      helm:
        valuesObject:
          # diagnosticMode:
          #   enabled: true
          # logging:
          #   level: ALL
          service:
            type: LoadBalancer
          resources:
            requests:
              cpu: 4
              memory: 2048Mi
            limits:
              cpu: 4
              memory: 2048Mi
          # livenessProbe:
          #   initialDelaySeconds: 500000
          # readinessProbe:
          #   initialDelaySeconds: 500000
    # - repoURL: oci://registry-1.docker.io/bitnamicharts/keycloak
    #   chart: keycloak
    #   targetRevision: 25.1.2
    #   helm:
    #     releaseName: keycloak
    #     valuesObject:
          # service:
          #   type: LoadBalancer
          # livenessProbe:
          #   enabled: false
          # ReadinessProbe:
          #   enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
