apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: oci://registry-1.docker.io/bitnamicharts/keycloak
      chart: keycloak
      targetRevision: 25.1.2
      helm:
        releaseName: keycloak
        valuesObject:
          # service:
          #   type: LoadBalancer
          # livenessProbe:
          #   enabled: false
          # ReadinessProbe:
          #   enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
