apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway-crds
      chart: kgateway-crds
      targetRevision: 2.3.0-main
      helm:
        releaseName: kgateway-crds
        valuesObject:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kgateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
