apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-eventing-websocket-source
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/UriZafrir/knative-eventing-websocket-source.git
      targetRevision: master
      path: yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: knative-eventing-websocket-source
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
