apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.konghq.com
      chart: kong
      targetRevision: 3.4.0
      helm:
        releaseName: kong
        valuesObject:
          manager:
            type: LoadBalancer
          admin:
            enabled: true
            type: NodePort
            http:
              nodePort: 32001
          env:
            admin_gui_url: "http://192.168.122.103:8002"
            admin_gui_api_url: "http://192.168.64.105:32001"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kong-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
