apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.konghq.com
      chart: kong
      targetRevision: 3.4.0
      helm:
        releaseName: kong
        valuesObject:
          manager:
            type: LoadBalancer
          admin:
            type: NodePort
            enabled: true
            http:
              nodePort: 32001
          env:
            ADMIN_GUI_URL: "https://192.168.64.105:32100"
            PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kong-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
