apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: langfuse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://langfuse.github.io/langfuse-k8s
      chart: langfuse
      targetRevision: 1.5.33
      helm:
        releaseName: langfuse
        valuesObject:
          langfuse:
            additionalEnv:
              - name: CLICKHOUSE_CLUSTER_ENABLED
                value: "false"
            web:
              service:
                type: LoadBalancer
            salt:
              secretKeyRef:
                name: "langfuse-salt"
                key: "salt"
            # NextAuth configuration
            nextauth:
              secret:
                secretKeyRef:
                  name: "langfuse-salt"
                  key: "salt"
          # redis:
          #   deploy: true
          #   host: "langfuse-redis-primary"
          #   auth:
          #     existingSecret: "langfuse-redis"
          #     existingSecretPasswordKey: "valkey-password"
          postgresql:
            deploy: false
            host: postgres-langfuse-rw.langfuse.svc.cluster.local
            auth:
              username: app
              database: app
              existingSecret: "postgres-langfuse-app"
              # -- The keys in the existing secret that contain the passwords. If using the default `postgres` user, both `userPasswordKey` and `adminPasswordKey` must be provided.
              secretKeys:
                userPasswordKey: password
          clickhouse:
            deploy: false
            host: "clickhouse-langfuse.langfuse.svc.cluster.local"
            auth:
              username: "langfuse_user" 
              # -- If you want to use an existing secret for the ClickHouse password, set the name of the secret here. (`clickhouse.auth.password` will be ignored and picked up from this secret).
              existingSecret: "langfuse-clickhouse-creds"
              # -- The key in the existing secret that contains the password.
              existingSecretKey: "password"
    - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      targetRevision: ubuntu
      path: extras/langfuse
  destination:
    server: "https://kubernetes.default.svc"
    namespace: langfuse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
