apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/BerriAI/litellm
    targetRevision: main
    path: deploy/charts/litellm-helm
    helm:
      releaseName: litellm
      valuesObject:
        db:
          deployStandalone: true
          useExisting: true
          # How to connect to the existing postgres server/cluster
          endpoint: litellm-rw.litellm.svc:5432
          secret:
            name: litellm-app
            usernameKey: username
            passwordKey: password
        service:
          type: LoadBalancer
        migrationJob:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: litellm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
