#first install iscsi
#apt-get install open-iscsi
#systemctl enable iscsid
#systemctl start iscsid
#systemctl status iscsid
#https://longhorn.io/docs/1.7.2/deploy/install/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.11.1
      helm:
        releaseName: longhorn
        valuesObject:
          defaultSettings:
            defaultDataPath: /mnt/data
          persistence:
            defaultClass: true
          preUpgradeChecker:
            jobEnabled: false
          service:
            ui:
              type: LoadBalancer
          #reduce all containers to 1 replica
          longhornUI:
            replicas: 1
          csi:
            attacherReplicaCount: 1
            # -- Replica count of the CSI Provisioner. When unspecified, Longhorn uses the default value ("3").
            provisionerReplicaCount: 1
            # -- Replica count of the CSI Resizer. When unspecified, Longhorn uses the default value ("3").
            resizerReplicaCount: 1
            # -- Replica count of the CSI Snapshotter. When unspecified, Longhorn uses the default value ("3").
            snapshotterReplicaCount: 1
          #for single node, make it not replicate storage
          persistence:
            defaultClassReplicaCount: 1
          defaultSettings:
            defaultReplicaCount: '{"v1":"1","v2":"1"}'

    - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      targetRevision: ubuntu
      path: extras/longhorn
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/ports/0/nodePort
