apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mender
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.mender.io
      chart: mender
      targetRevision: 7.6.2
      # - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      #   targetRevision: ubuntu
      #   path: extras/mender-helm
      helm:
        releaseName: mender
        valuesObject:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/issuer: "selfsigned-issuer"
            ingressClassName: traefik
            path: /
            hosts:
              - mender.192.168.122.108.nip.io
            tls:
              # this secret must exists or it can be created from a working cert-manager instance
              - secretName: mender-ingress-tls
                hosts:
                  - mender.192.168.122.108.nip.io

          # nats:
          #   cluster:
          #     enabled: true
          #     replicas: 1
          gui:
            service:
              type: LoadBalancer
          global:
            s3:
              existingSecret: seaweedfs-mender-creds
            url: "192.168.122.106"
          api_gateway:
            # dashboard: true
            service:
              type: LoadBalancer
            storage_proxy:
              enabled: true
              url: "http://seaweedfs-s3.mender.svc:8333"
              customRule: "PathRegexp(^/mender-bucket)"
            # serviceNamespace: "mender"
    - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      targetRevision: ubuntu
      path: extras/mender
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mender
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
