apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meshery
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://meshery.io/charts/
      chart: meshery
      targetRevision: 0.8.178
      helm:
        releaseName: meshery
        valuesObject:
    # - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
    #   targetRevision: HEAD
    #   path: extras/meshery
  destination:
    server: "https://kubernetes.default.svc"
    namespace: meshery
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
