apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # annotations:
  #   argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server/
      chart: metrics-server
      targetRevision: 3.13.0
      helm:
        releaseName: metrics-server
        valuesObject:
        args:
          - --kubelet-insecure-tls
    # - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
    #   targetRevision: HEAD
    #   path: extras/metrics-server
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
