apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: n8n
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 1.16.36
    helm:
      releaseName: n8n
      valuesObject:
        # image:
          # repository: urizaf/n8n
          # tag: latest
        main:
          main.extraEnvVars:
            N8N_SECURE_COOKIE:
              value: "false"
            # NODE_FUNCTION_ALLOW_EXTERNAL:
            #   value: "@rxap/n8n-nodes-litellm"
        service:
          type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
