apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: n8n
    repoURL: oci://8gears.container-registry.com/library/n8n
    targetRevision: 1.0.10
    helm:
      releaseName: n8n
      valuesObject:
        main:
          # command:
          #   - /bin/sh
          #   - -c
          #   - "cd /usr/local/lib/node_modules/n8n && npm install @rxap/n8n-nodes-litellm && tini -- /docker-entrypoint.sh"
          extraEnv:
            N8N_SECURE_COOKIE:
              value: "false"
            NODE_FUNCTION_ALLOW_EXTERNAL:
              value: "@rxap/n8n-nodes-litellm"
          service:
            type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
