#su -s /bin/bash www-data
#php occ config:system:set trusted_domains 2 --value=192.168.100.2

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  nextcloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
      repoURL: https://github.com/UriZafrir/home-lab-cluster.git
      targetRevision: HEAD
      path: extras/nexcloud
  destination:
    server: "https://kubernetes.default.svc"
    namespace:  nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
