apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  nextcloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart:  nextcloud
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 6.6.5
    helm:
      releaseName:  nextcloud
      valuesObject:
        service:
          type: LoadBalancer
        persistence:
          enabled: true
        # collabora:
        #   enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace:  nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
