apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: nvidia-gpu-operator
    repoURL: https://helm.ngc.nvidia.com/nvidia
    targetRevision: 26.3.1
    helm:
      releaseName: nvidia-gpu-operator
      valuesObject:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nvidia-gpu-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
