apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  project: default
  source:
    chart: ollama
    repoURL: https://otwld.github.io/ollama-helm/
    targetRevision: 1.56.0
    helm:
      releaseName: ollama
      valuesObject:
        httpRoute:
          enabled: true
          hostnames:
            - qwen2.5-coder-3b.192.168.122.200.nip.io
          parentRefs:
            - name: kgateway-gateway
              namespace: kgateway-system
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /api
        ollama:
          gpu:
            enabled: true
          models:
            pull:
              - qwen2.5-coder:3b
            run:
              - qwen2.5-coder:3b
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
