apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.147.1
      helm:
        releaseName: opentelemetry-collector
        valuesObject:
          mode: daemonset
          image:
            repository: otel/opentelemetry-collector-contrib
          presets:
            logsCollection:
              enabled: true
              includeCollectorLogs: true
            hostMetrics:
              enabled: true
            kubernetesAttributes:
              enabled: true
            kubeletMetrics:
              enabled: true
          # Add environment variable for the HyperDX API key
          extraEnvs:
            - name: HYPERDX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: clickstack-app-secrets
                  key: api-key
          config:
            extensions:
              health_check:
                endpoint: :13133
              bearertokenauth:
                token: ${HYPERDX_API_KEY}
            processors:
              batch:
                send_batch_size: 1000
                timeout: 10s
            exporters:
              otlphttp:
                endpoint: "http://clickstack-otel-collector.clickstack-operators-system.svc:4318"
                tls:
                  insecure: true
                auth:
                  authenticator: bearertokenauth
              # otlp_grpc:
              #   endpoint: "clickstack-otel-collector.clickstack-operators-system.svc:4317"
              #   tls:
              #     insecure: true
              #   auth:
              #     authenticator: bearertokenauth
            service:
              extensions: [health_check, bearertokenauth]
              pipelines:
                metrics:
                  exporters:
                    - otlphttp
                    - debug
                  processors:
                    - batch
                  receivers:
                    - hostmetrics
                logs:
                  exporters:
                    - otlphttp
                    - debug
                  processors:
                    - batch
                  receivers:
                    - filelog
    # - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
    #   targetRevision: HEAD
    #   path: extras/opentelemetry-collector
  destination:
    server: "https://kubernetes.default.svc"
    namespace: clickstack-operators-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
