apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.147.1
      helm:
        releaseName: opentelemetry-collector
        valuesObject:
          mode: daemonset
          image:
            repository: otel/opentelemetry-collector-contrib
          extraEnvs:
            - name: CLICKHOUSE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: altinity-clickhouse-operator
                  namespace: altinity-clickhouse-operator
                  key: username
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: altinity-clickhouse-operator
                  namespace: altinity-clickhouse-operator
                  key: password
          presets:
            logsCollection:
              enabled: true
              includeCollectorLogs: true
            hostMetrics:
              enabled: true
            kubernetesAttributes:
              enabled: true    
              extractAllPodLabels: false
              extractAllPodAnnotations: false
            kubeletMetrics:
              enabled: true
            kubernetesEvents:
              enabled: true
            clusterMetrics:
              enabled: true

          config:
            processors:
              batch:
                send_batch_size: 1000
                timeout: 10s
            exporters:
              clickhouse:
                endpoint: "http://chi-clickhouse-clickhouse-0-0.altinity-clickhouse-operator.svc:8123"
                database: "default"
                username: "${CLICKHOUSE_USERNAME}"
                password: "${CLICKHOUSE_PASSWORD}"
                ttl: 48h # Optional: sets data retention (e.g., 30 days)
                # Optional: table names
                traces_table_name: "traces"
                logs_table_name: "logs" 
                metrics_table_name: "metrics"
            service:
              pipelines:
                metrics:
                  exporters:
                    - clickhouse
                    - debug
                  processors:
                    - batch
                  receivers:
                    - hostmetrics
                    - kubeletstats 
                    - k8s_cluster
                logs:
                  exporters:
                    - clickhouse
                    - debug
                  processors:
                    - batch
                  receivers:
                    - filelog
    # - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
    #   targetRevision: HEAD
    #   path: extras/opentelemetry-collector
  destination:
    server: "https://kubernetes.default.svc"
    namespace: altinity-clickhouse-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
