apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://openebs.github.io/openebs
      chart: openebs
      targetRevision: 4.5.0-develop
      helm:
        releaseName: openebs
        valuesObject:
          loki:
            singleBinary:
              replicas: 1
            minio:
              replicas: 1
            loki:
              commonConfig: 
                replication_factor: 1
          engines:
            replicated:
              mayastor:
                enabled: false
          # mayastor:
          #   etcd:
          #     auth:
          #       token:
          #         enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
