apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.147.1
      helm:
        releaseName: opentelemetry-collector
        valuesObject:
          service:
            enabled: true
          mode: daemonset
          # serviceMonitor:
          #   enabled: true
          # additionalLabels:
          #     release: kube-prometheus-stack
          # ports:
          #   metrics:
          #     enabled: true
          image:
            repository: otel/opentelemetry-collector-contrib
          presets:
            logsCollection:
              enabled: true
              includeCollectorLogs: true
            hostMetrics:
              enabled: true
          config:
            processors:
              deltatocumulative:
                max_stale: 5m
            exporters:
              otlphttp/vmcluster:
                metrics_endpoint: http://vminsert-vmcluster.victoria-metrics-operator.svc:8480/insert/0/opentelemetry/v1/metrics
                compression: gzip
                encoding: proto
              otlphttp/vlcluster:
                logs_endpoint: http://vlinsert-vlcluster.victoria-metrics-operator.svc:9481/insert/opentelemetry/v1/logs
                compression: gzip
                encoding: proto
            service:
              pipelines:
                metrics:
                  exporters:
                    - debug
                  processors:
                    - memory_limiter
                    - batch
                    - deltatocumulative
                  receivers:
                    - otlp
                    # if internalTelemetryViaOTLP.metrics.enabled = true, prometheus receiver will be removed
                    - prometheus
                      
    # - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
    #   targetRevision: HEAD
    #   path: extras/opentelemetry-collector
  destination:
    server: "https://kubernetes.default.svc"
    namespace: opentelemetry-collector-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
