apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.147.1
      helm:
        releaseName: opentelemetry-collector
        valuesObject:
          mode: daemonset
          image:
            repository: otel/opentelemetry-collector-contrib
          presets:
            logsCollection:
              enabled: true
              includeCollectorLogs: true
            hostMetrics:
              enabled: true
            kubernetesAttributes:
              enabled: true
            kubeletMetrics:
              enabled: true
          extraVolumes:
            - name: hostfs
              hostPath:
                path: /
          extraVolumeMounts:
            - name: hostfs
              mountPath: /hostfs
              readOnly: true
              mountPropagation: HostToContainer
          config:
            processors:
              deltatocumulative:
                max_stale: 5m
            exporters:
              otlphttp/vmcluster:
                metrics_endpoint: http://vminsert-vmcluster.victoria-metrics-operator.svc:8480/insert/0/opentelemetry/v1/metrics
                compression: gzip
                encoding: proto
              otlphttp/vlcluster:
                logs_endpoint: http://vlinsert-vlcluster.victoria-metrics-operator.svc:9481/insert/opentelemetry/v1/logs
                compression: gzip
                encoding: proto
            service:
              pipelines:
                metrics:
                  exporters:
                    - otlphttp/vmcluster
                    - debug
                  processors:
                    # - memory_limiter
                    # - batch
                    - deltatocumulative
                  receivers:
                    - hostmetrics
                logs:
                  exporters:
                    - otlphttp/vlcluster
                    - debug
                  # processors:
                  #   - memory_limiter
                  #   - batch
                  receivers:
                    # - otlp
                    - filelog
    # - repoURL: https://github.com/UriZafrir/home-lab-cluster.git
    #   targetRevision: HEAD
    #   path: extras/opentelemetry-collector
  destination:
    server: "https://kubernetes.default.svc"
    namespace: opentelemetry-collector-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
