apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsiforce-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/UriZafrir/opsiforce.git
      targetRevision: main
      path: helm/opsiforce
      helm:
        releaseName: external-secrets
        valuesObject:
          storage:
            className: local-path
          valkey:
            affinity: {}
          agent:
            affinity: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: opsiforce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
