#curl https://192.168.100.4:32400/web/ -vvv
#curl https://in.uri.work.gd/plex/web -vvv --insecure
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: plex
    repoURL: https://utkuozdemir.org/helm-charts
    targetRevision: 2.1.1
    helm:
      releaseName: plex
      valuesObject:
        # image:
        #   repository: lscr.io/linuxserver/plex
        #   tag: latest
        service:
          type: LoadBalancer 
        persistence:
          data: 
            enabled: true
            isPvc: false
            customVolume:
              hostPath:
                path: /mnt/data/jellyfin-data/
        ingress:
          # -- Expose the app using an ingress
          enabled: true
          # -- Ingress class name
          className: "nginx"
          # -- Annotations for the ingress
          annotations:
            cert-manager.io/cluster-issuer: "ca-issuer"
            nginx.ingress.kubernetes.io/app-root: /web
          # -- Ingress hosts configuration
          # @default -- see [values.yaml](values.yaml)
          hosts:
            - host: in.uri.work.gd
              paths:
                - path: /plex
                  pathType: Prefix
                  backend:
                    service:
                      name: plex
                      port:
                        number: 32400
          # -- The TLS configuration for the Ingress
          tls:
          - hosts:
            - in.uri.work.gd
            secretName: jellyfin-tls
        
  destination:
    server: "https://kubernetes.default.svc"
    namespace: plex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

