#https://www.civo.com/learn/sealed-secrets-in-git#:~:text=Applying%20the%20Sealed%20Secret,-Step%201%3A%20Apply&text=Use%20the%20kubectl%20apply%20command,file%20to%20your%20Kubernetes%20cluster.&text=This%20command%20will%20create%20a%20Sealed%20Secret%20in%20the%20cluster.&text=These%20commands%20will%20list%20the,secrets%20in%20the%20cluster%2C%20respectively.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets/
      chart: sealed-secrets
      targetRevision: 2.17.1
      helm:
        releaseName: sealed-secrets
      valuesObject:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
