apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.signoz.io
      chart: signoz
      targetRevision: 0.104.0
      helm:
        releaseName: signoz
        valuesObject:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: signoz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
