apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: default
  sources:
    - repoURL: https://temporalio.github.io/helm-charts
      chart: temporal
      targetRevision: 1.0.0
      helm:
        releaseName: temporal
        valuesObject:
          server:
            frontend:
              service:
                type: LoadBalancer
        datastores:
          default:
            sql:
              pluginName: postgres17
              driverName: postgres17
              databaseName: temporal
              connectAddr: "postgres.example.com:5432"
              connectProtocol: "tcp"
              user: temporal_user
              existingSecret: temporal-db-secret
              secretKey: password
  destination:
    server: "https://kubernetes.default.svc"
    namespace: temporal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
