apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://temporalio.github.io/helm-charts
      chart: temporal
      targetRevision: 0.68.1
      helm:
        releaseName: temporal
        valuesObject:
          server:
            replicaCount: 1 
          cassandra:
            config:
              cluster_size: 1 
          elasticsearch:
            replicas: 1 
          prometheus:
            enabled: false 
          grafana:
            enabled: false 
          elasticsearch:
            imageTag: 7.17.26
  destination:
    server: "https://kubernetes.default.svc"
    namespace: temporal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
