apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: default
  sources:
    - repoURL: https://temporalio.github.io/helm-charts
      chart: temporal
      targetRevision: 1.0.0
      helm:
        releaseName: temporal
        valuesObject:
          server:
            replicaCount: 1
            frontend:
              service:
                type: LoadBalancer
          config:
            persistence:
              defaultStore: default
              visibilityStore: visibility
              numHistoryShards: 512
              datastores:
                default:
                  sql:
                    pluginName: postgres12
                    databaseName: temporal
                    connectAddr: "postgres-rw.temporal.svc.cluster.local:5432"
                    connectProtocol: "tcp"
                    existingSecret: postgres-app
                    secretKey: password
                    user: app
                visibility:
                  sql:
                    pluginName: postgres12
                    databaseName: temporal_visibility
                    connectAddr: "postgres-rw.temporal.svc.cluster.local:5432"
                    connectProtocol: "tcp"
                    existingSecret: postgres-app
                    secretKey: password
                    user: app
  destination:
    server: "https://kubernetes.default.svc"
    namespace: temporal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
