apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ztunnel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    chart: ztunnel
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.27.2
    # helm:
    #   valuesObject:
    #     profile: ambient
    #     global:
    #       platform: k3s
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    # syncOptions:
    # - CreateNamespace=true
  # ignoreDifferences:
  #   - group: admissionregistration.k8s.io
  #     kind: ValidatingWebhookConfiguration
  #     name: istio-validator-istio-system
  #     jsonPointers:
  #       - /webhooks/0/failurePolicy
  #   - group: admissionregistration.k8s.io
  #     kind: ValidatingWebhookConfiguration
  #     name: istiod-default-validator
  #     jsonPointers:
  #       - /webhooks/0/failurePolicy
