apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: startechnica
  namespace: flux-system
spec:
  interval: 1h
  url: https://startechnica.github.io/apps
---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: multus
#   namespace: kube-system
# spec:
#   interval: 1h
#   chart:
#     spec:
#       chart: multus
#       version: 3.9.3
#       sourceRef:
#         kind: HelmRepository
#         name: startechnica
#         namespace: flux-system