apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-mender-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: seaweedfs-mender-creds
  dataFrom:
  - extract:
      key: seaweedfs-mender-creds