apiVersion: v1
kind: Namespace
metadata:
  name: harbor-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor-system
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: '1.x.x'
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  values:
    # Configure Harbor settings here
    expose:
      type: loadBalancer
    persistence:
      persistentVolumeClaim:
        storageClass: local-path
