#https://quay.io/repository/containerdisks/fedora
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora
spec:
  runStrategy: Always
  template:
    metadata:
      labels: 
        kubevirt.io/domain: vm-fedora
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinit
          interfaces:
            - name: default
              masquerade: {}
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: true
        resources:
          requests:
            memory: 1Gi
      networks:
      - name: default
        pod: {} # Stock pod network
      terminationGracePeriodSeconds: 180
      volumes:
      - containerDisk:
          image: quay.io/containerdisks/fedora:41
        name: containerdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            users:
              - name: fedora
                ssh-authorized-keys:
                    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICjfyR0TesyI0zSn92lLgsjTzTTkL8Ox9rBDKX/JThah
            ssh_pwauth: True
            disable_root: false
            sudo: ALL=(ALL) NOPASSWD:ALL #didnt work
            password: fedora
            chpasswd:
              expire: False
              list: |-
                fedora:fedora
                root:fedora
        name: cloudinit
---
apiVersion: v1
kind: Service
metadata:
  name: vmsshservice
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    kubevirt.io/domain: vm-fedora
  type: LoadBalancer
