#https://quay.io/repository/containerdisks/fedora
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora
  labels:
    kubevirt.io/vm: vm-fedora
spec:
  runStrategy: Always
  template:
    metadata:
      labels: 
        kubevirt.io/domain: vm-fedora
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinit
          interfaces:
            - name: default
              masquerade: {}
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: true
        resources:
          requests:
            memory: 1Gi
      networks:
      - name: default
        pod: {} # Stock pod network
        machine:
          type: ""
      terminationGracePeriodSeconds: 180
      volumes:
      - containerDisk:
          image: quay.io/containerdisks/fedora:41
        name: containerdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            users:
              - name: fedora
                ssh-authorized-keys:
                    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICjfyR0TesyI0zSn92lLgsjTzTTkL8Ox9rBDKX/JThah
            ssh_pwauth: True
            disable_root: false
            # sudo: ALL=(ALL) NOPASSWD:ALL #didnt work
            password: fedora
            chpasswd:
              expire: False
              list: |-
                fedora:fedora
                root:fedora
        name: cloudinit
---
apiVersion: v1
kind: Service
metadata:
  name: vmsshservice
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    kubevirt.io/domain: vm-fedora
  type: LoadBalancer
# apiVersion: v1
# kind: Service
# metadata:
#   name: vmsshservice
# spec:
#   externalTrafficPolicy: Cluster
#   ports:
#   - name: nodeport
#     nodePort: 30000
#     port: 27017
#     protocol: TCP
#     targetPort: 22
#   selector:
#     kubevirt.io/vm: vm-fedora
#   type: NodePort


# apiVersion: kubevirt.io/v1
# kind: VirtualMachine
# metadata:
#   labels:
#     kubevirt.io/vm: vm-cirros
#   name: vm-cirros
# spec:
#   runStrategy: Once
#   template:
#     metadata:
#       labels:
#         kubevirt.io/vm: vm-cirros
#     spec:
#       domain:
#         cpu:
#           cores: 4
#         resources:
#           requests:
#             memory: 4G
#         devices:
#           disks:
#           - disk:
#               bus: virtio
#             name: containerdisk
#           - disk:
#               bus: virtio
#             name: cloudinitdisk
#           interfaces:
#             - name: default
#               masquerade: {}
#       networks:
#       - name: default
#         pod: {} # Stock pod network
#         machine:
#           type: ""
#       terminationGracePeriodSeconds: 0
#       volumes:
#       - name: containerdisk
#         containerDisk:
#           image: kubevirt/cirros-container-disk-demo:latest
#       - cloudInitNoCloud:
#           userDataBase64: IyEvYmluL3NoCgplY2hvICdwcmludGVkIGZyb20gY2xvdWQtaW5pdCB1c2VyZGF0YScK
#         name: cloudinitdisk

